import { ProjectGenerator } from './dist/generator.js';

const generator = new ProjectGenerator();

const result = await generator.scaffold({
  projectName: 'test-api',
  template: 'typescript-express',
  outputPath: '../../test-output',
  options: {
    database: 'postgresql',
    authentication: 'jwt',
    author: 'Test User',
    description: 'Test API generated by Project Scaffolder',
    includeDocker: true,
    includeTests: true,
    includeCICD: true,
  },
});

console.log('SUCCESS:', result.success);
console.log('Project Path:', result.projectPath);
console.log('Files Created:', result.filesCreated.length);
console.log('\nNext Steps:');
result.nextSteps.forEach((step, idx) => console.log(`${idx + 1}. ${step}`));

if (!result.success) {
  console.error('ERROR:', result.error);
}
