import { ProjectGenerator } from './dist/generator.js';

const generator = new ProjectGenerator();

// Test Next.js template
const result = await generator.scaffold({
  projectName: 'test-nextjs-app',
  template: 'typescript-nextjs',
  outputPath: '../../test-output',
  options: {
    author: 'Test User',
    description: 'Test Next.js app generated by Project Scaffolder',
    includeDocker: false,
    includeTests: true,
    includeCICD: false,
  },
});

console.log('=== Next.js Template Test ===');
console.log('SUCCESS:', result.success);
console.log('Files Created:', result.filesCreated.length);
console.log('\nFiles:');
result.filesCreated.forEach(f => console.log(`  - ${f}`));

if (!result.success) {
  console.error('ERROR:', result.error);
}
