import { ProjectGenerator } from './dist/generator.js';

const generator = new ProjectGenerator();

// Test FastAPI template
const result = await generator.scaffold({
  projectName: 'test-fastapi-app',
  template: 'python-fastapi',
  outputPath: '../../test-output',
  options: {
    author: 'Test User',
    description: 'Test FastAPI app generated by Project Scaffolder',
    database: 'postgresql',
    includeDocker: false,
    includeTests: true,
    includeCICD: false,
  },
});

console.log('=== FastAPI Template Test ===');
console.log('SUCCESS:', result.success);
console.log('Files Created:', result.filesCreated.length);
console.log('\nFiles:');
result.filesCreated.forEach(f => console.log(`  - ${f}`));

if (!result.success) {
  console.error('ERROR:', result.error);
}
